spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc8th
    username: root
    password: Ksy0780@
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        generate_statistics: true
      javax:
        persistence:
          sharedCache:
          mode: ENABLE_SELECTIVE